### ISSUE TITLE
Alignments of all sentences on the same line

### ISSUE THREAD

**Issue by mdtux89** [alopez/hermes-aligner#1]
Hi!

There's a problem with the download feature. From the code in `hermes.py` it looks like the alignments of a sentence should be separated by the alignments of the next sentence with a newline. That doesn't happen: it generates an one-line string with the alignments of all sentences together.

Marco

**Comment by alopez** [comment]
I'm having trouble reproducing this. It would be good to get an example output file demonstrating the problem.

**Comment by mdtux89** [comment]
Sure.
`0-0 0-1 3-2 3-2 4-3 5-4 7-6 8-7 9-8 9-9 9-10 9-11 9-12 9-13 9-14 10-8 10-9 10-10 10-11 10-12 10-13 10-14 11-8 11-9 11-10 11-11 11-12 11-13 11-14 12-8 12-9 12-10 12-11 12-12 12-13 12-14 13-8 13-9 13-10 13-11 13-12 13-13 13-14 14-8 14-9 14-10 14-11 14-12 14-13 14-14 15-8 15-9 15-10 15-11 15-12 15-13 15-14 19-18 20-17 23-19 24-20 25-21 26-23 27-22 29-26 30-29 31-30 33-31 34-32 1-0 1-1 2-0 2-1 4-3 6-5 7-6 9-7 10-10 12-12 13-13 13-14 15-15 15-16 16-15 16-16 17-13 17-14 18-17 19-19 19-20 20-19 20-20 23-18 23-21 24-18 24-21 26-25 26-26 27-25 27-26 29-29 30-31 31-32 0-0 0-1 0-2 1-7 7-4 9-8 10-9 11-10 15-13 16-14 17-15 0-0 0-1 0-2 1-3 2-4 4-7 4-8 5-9 6-10 8-11 11-13 12-14 15-15 19-18 20-17 22-21 23-23 24-24 25-25 26-26 27-27 28-28 29-29 30-31 31-30 32-32 33-33 34-34 36-37 37-36 38-39 0-0 1-3 2-5 0-0 0-1 0-2 2-5 3-7 4-10 5-9 6-11 7-12 8-16 9-17 11-15 12-14 13-18 0-1 1-3 2-5 3-6 4-7 6-9 7-13 7-14 8-10 9-11 10-15 11-16 13-17 14-18 17-20 18-21 19-21 20-21 22-22 25-25 27-28 28-29 29-30 30-32 30-33 35-35 36-36 38-38 39-40 40-40 42-43 43-45 44-46 0-0 2-2 3-3 4-4 5-5 6-6 7-7 8-8 9-9 10-10 11-12 12-13 13-14 14-15 15-17 17-16 18-18 19-21 22-20 23-20 25-23 25-24 26-25 26-26 29-28 29-29 32-30 33-30 34-31 0-0 1-1 2-3 3-4 0-1 1-2 2-3 3-4 8-11 9-11 12-5 12-6 13-7 17-13 19-14 21-20 22-19 23-19 24-21 0-0 1-1 2-3 5-5 6-6 7-7 8-9 9-10 10-12 11-11 12-13 0-0 1-1 2-3 3-4 4-5 5-6 6-7 7-8 8-9 11-11 13-12 14-13 15-16 16-17 17-18 18-20 19-19 21-21 24-26 25-22 28-25 29-25 32-30 33-30 34-31 35-33 38-32 39-34 0-0 1-1 3-2 4-3 4-4 5-3 5-4 6-5 7-6 8-7 9-8 10-9 14-11 15-12 16-13 17-14 0-1 2-2 5-4 6-6 7-5 8-7 10-8 12-13 13-14 18-17 22-21 0-0 1-2 2-3 3-4 7-7 8-8 9-9 10-10 11-11 12-12 13-13 13-14 14-13 14-14 15-13 15-14 16-15 1-0 1-1 2-0 2-1 3-0 3-1 4-2 6-3 7-5 8-6 9-7 15-8 20-13 21-14 21-15 22-17 23-16 24-18 25-19 26-20 27-21 29-23 30-24 30-25 31-24 31-25 32-26 34-28 35-28 36-29 40-32 43-36 44-37 57-39 58-40 63-41 64-42 64-43 65-42 65-43 66-44 67-46 68-47 69-48 69-49 70-48 70-49 71-50 72-51 73-52 0-1 1-2 2-5 3-3 9-4 13-7 14-8 15-9 15-10 16-9 16-10 18-11 19-12 20-13 21-15 22-14 23-17 24-18 0-0 1-1 2-2 4-4 5-3 7-8 8-7 9-9 11-10 13-12 15-14 16-15 17-16 19-17 20-18 21-19 24-20 24-21 25-20 25-21 27-22 29-25 29-26 33-24 34-27 0-0 2-12 2-13 12-4 13-3 14-14 1-0 1-1 2-2 3-4 4-6 5-9 5-10 9-12 11-15 11-16 14-17 0-0 1-0 3-1 4-2 6-3 7-4 13-5 13-6 14-5 14-6 15-10 16-12 17-14 19-16 20-19 22-17 23-20 24-21 25-24 27-25 28-26 29-27 30-29 31-31 0-0 6-4 9-5 10-7 13-6 14-8 16-10 17-11 18-13 18-14 18-15 18-16 19-13 19-14 19-15 19-16 20-17 21-18 25-21 26-20 27-19 28-23 32-28 33-30 34-31 35-32 36-33 37-34 38-35 40-38 41-39 0-1 1-2 2-4 3-5 4-6 5-7 6-8 11-11 12-14 15-12 15-13 16-12 16-13 18-15 20-17 21-18 22-19 0-0 1-3 1-4 3-8 4-7 6-9 7-10 8-11 9-12 1-0 3-1 4-2 5-3 6-4 7-5 8-6 9-8 9-9 10-8 10-9 11-10`

**Comment by alopez** [comment]
Can you also send me the source file that you're aligning?

**Comment by mdtux89** [comment]
Sure. [sents.txt](https://github.com/alopez/hermes-aligner/files/107112/sents.txt)

**Comment by alopez** [comment]
Based on discussion, it's likely that commit 8a412d0c07f214205bca22afe467088086d8aa6c fixes this issue, but let me know if it persists.
